# TCP listener — para Node.js backend y Raspberry Pi
listener 1883
allow_anonymous true

# WebSocket listener — fallback para clientes web directos
listener 9001
protocol websockets
allow_anonymous true

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type all