apiVersion: 1

datasources:
  - name: marcusolsson-json-datasource
    type: marcusolsson-json-datasource
    uid: efg9puqoh4tmoa
    url: http://backend:4000
    access: proxy
    isDefault: true
    editable: true

    jsonData:
      httpHeaderName1: x-grafana-key
      httpHeaderName2: "Content-Type"

    secureJsonData:
      httpHeaderValue1: ecosort_grafana_key_2026
      httpHeaderValue2: "application/json"